### ISSUE TITLE
Events in different status should be marked or separated in activities overview page

### ISSUE THREAD

**Issue by HardisonSY** [EWHatCYCU/EWHWebsite#7]
Currently displaying of activities overview page may make it difficult for users to identify the status of events, events in different status (e.g. `On going`, `Future`, `Past`) should be separated in different block or should be marked so that users can easily identify which event they can register, and which event is past event.

Discussed in the meeting at May, 20th, 2015.

**Comment by mitour** [comment]
Preview 那頁想直接用一層 mask 罩起來，刷淡或是再加上「已結束」字樣，考慮用偽元素實現。
至於單頁就多增加一長條區塊表示狀態，會在 banner 下方，並以顯眼的的色調凸顯。
